### ISSUE TITLE
divide-events.py complains about newline

### ISSUE THREAD

**Issue by pseudobacon** [bxabi/facebook-events-ics#3]
Running on python 2.7

![image](https://user-images.githubusercontent.com/12183854/73418553-1a9b3980-4370-11ea-8112-19386c7a5db5.png)

**Comment by pseudobacon** [comment]
Okay so this is resolved by using python3, but then should we change the python command in divide-events.py to python3?

**Comment by bxabi** [comment]
It depends on the distribution you use I think, in mine python is python3 by default. I wonder how common that is, which linux are you using?

**Comment by pseudobacon** [comment]
CrunchBangPlusPlus, so Debian based. On Ubuntu python refers to 2.7 and according to the python website [https://www.python.org/dev/peps/pep-0394/#history-of-this-pep](url) it will always refer to 2.7

**Comment by bxabi** [comment]
I changed it to 'python3' in the script, this way it should be compatible with more or all distros.
