### ISSUE TITLE
Default config folder should be created if it doesn't exist

### ISSUE THREAD

**Issue by pseudobacon** [bxabi/facebook-events-ics#4]
So the script fails for me because I don't have a .config folder on my system

![image](https://user-images.githubusercontent.com/12183854/73419354-e7a67500-4372-11ea-8884-ed0e3466997a.png)

Maybe it would be a good idea to create the folder before/on download of the ics file?

**Comment by bxabi** [comment]
yes that's totally right, I updated the script.
